#pragma once
#ifndef MOVE_ALLOWLIST_DEFINITIONS
#define MOVE_ALLOWLIST_DEFINITIONS

#define UPTOWN_DATABASE_ENTRY_NOT_EXISTING -100


enum MoverStatus
{
	MOVERSTATUS_NEVER_ALLOWED = 1,
	MOVERSTATUS_ALWAYS_ALLOWED,
	MOVERSTATUS_ENUM_END
};

#endif